server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8181

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    com.yasith: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
# Enable following for file appender
    - type: file
      currentLogFilename: logs/dropwizard-swagger.log #<path to log file>/<filename.log>
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: logs/dropwizard-swagger-%d.log #<path to log file >/< archive filename.log>
      archivedFileCount: 5
      timeZone: UTC

swagger:
  resourcePackage: com.yasith.dropwizardswagger.api